Repository magento/magento-cloud-docker, pull requests merged in 2019-11, with the labels that each got.

#92 MAGECLOUD-3978: [Spike][Cloud Docker] DB data should persist in a volume
  src/Compose/DeveloperBuilder.php
  src/Compose/ProductionBuilder.php
Labels: Release: 1.0.0, approved

#101 Added optional argument to expose DB port
  src/Command/BuildCompose.php
  src/Compose/ProductionBuilder.php
Labels: Partner: Zilker Technology, Release: 1.0.0, approved, community, improvement, partners-contribution

#96 MAGECLOUD-457: Add contribution guidelines
  .github/CONTRIBUTING.md
Labels: Release: 1.0.0, review

#89 MAGECLOUD-4040: Add selenium image to run MFTF on local machine with similar to cloud environment
  .travis.yml
  images/nginx/1.9/Dockerfile
  images/nginx/1.9/docker-entrypoint.sh
  images/nginx/1.9/etc/vhost.conf
  images/php/7.1-cli/Dockerfile
  images/php/7.1-cli/bin/magento-command
  images/php/7.1-cli/bin/mftf-command
  images/php/7.2-cli/Dockerfile
  images/php/7.2-cli/bin/magento-command
  images/php/7.2-cli/bin/mftf-command
  images/php/7.3-cli/Dockerfile
  images/php/7.3-cli/bin/magento-command
  images/php/7.3-cli/bin/mftf-command
  images/php/cli/Dockerfile
  images/php/cli/bin/magento-command
  images/php/cli/bin/mftf-command
  src/Command/BuildCompose.php
  src/Compose/DeveloperBuilder.php
  src/Compose/FunctionalBuilder.php
  src/Compose/ProductionBuilder.php
  src/Service/ServiceFactory.php
  src/Service/ServiceInterface.php
Labels: Release: 1.0.0, approved
