Repository magento/magento-cloud-docker, pull requests merged in 2019-06, with the labels that each got.

#26 MAGECLOUD-3446: Add ICU and Phonetic Plugins to Elasticsearch Docker image
  elasticsearch/1.7/Dockerfile
  elasticsearch/2.4/Dockerfile
  elasticsearch/5.2/Dockerfile
  elasticsearch/6.5/Dockerfile
Labels: qa

#25 MAGECLOUD-3357: [Cloud Docker] Changes in .magento.app.yaml should affect php modules
  composer.json
  composer.lock
  data/php-cli/Dockerfile
  data/php-cli/docker-entrypoint.sh
  data/php-extensions.php
  data/php-fpm/Dockerfile
  data/php-fpm/docker-entrypoint.sh
  php/7.0-cli/Dockerfile
  php/7.0-cli/docker-entrypoint.sh
  php/7.0-fpm/Dockerfile
  php/7.0-fpm/docker-entrypoint.sh
  php/7.1-cli/Dockerfile
  php/7.1-cli/docker-entrypoint.sh
  php/7.1-fpm/Dockerfile
  php/7.1-fpm/docker-entrypoint.sh
  php/7.2-cli/Dockerfile
  php/7.2-cli/docker-entrypoint.sh
  php/7.2-fpm/Dockerfile
  php/7.2-fpm/docker-entrypoint.sh
  src/Command/Generate/Php.php
Labels: review

#27 MAGECLOUD-3832: [Cloud Docker] Update libsodium library
  data/php-cli/Dockerfile
  data/php-extensions.php
  data/php-fpm/Dockerfile
  php/7.0-cli/Dockerfile
  php/7.0-fpm/Dockerfile
  php/7.1-cli/Dockerfile
  php/7.1-fpm/Dockerfile
  php/7.2-cli/Dockerfile
  php/7.2-fpm/Dockerfile
  src/Command/Generate/Php.php
Labels: approved
