Repository magento/magento-cloud-docker, pull requests merged in 2019-08, with the labels that each got.

#34 Add Nodejs & Grunt-cli to PHP-CLI Images
  data/php-cli/Dockerfile
  php/7.0-cli/Dockerfile
  php/7.0-cli/bin/run-hooks
  php/7.1-cli/Dockerfile
  php/7.1-cli/bin/run-hooks
  php/7.2-cli/Dockerfile
  php/7.2-cli/bin/run-hooks
  src/Command/Generate/Php.php
Labels: qa

#36 MAGECLOUD-3996: [Cloud Docker] Add Separate Post-deploy Hook to Cloud Docker
  images/php/7.0-cli/Dockerfile
  images/php/7.0-cli/bin/cloud-deploy
  images/php/7.0-cli/bin/cloud-post-deploy
  images/php/7.1-cli/Dockerfile
  images/php/7.1-cli/bin/cloud-deploy
  images/php/7.1-cli/bin/cloud-post-deploy
  images/php/7.2-cli/Dockerfile
  images/php/7.2-cli/bin/cloud-deploy
  images/php/7.2-cli/bin/cloud-post-deploy
  images/php/7.3-cli/bin/cloud-deploy
  images/php/7.3-cli/bin/cloud-post-deploy
  images/php/cli/Dockerfile
  images/php/cli/bin/cloud-deploy
  images/php/cli/bin/cloud-post-deploy
Labels: approved

#37 Add pound.cfg file and TimeOut and RewriteLocation directives in cfg
  images/tls/Dockerfile
  images/tls/pound.cfg
Labels: approved, community, improvement, qa

#39 Updated README.md
  README.md
Labels: approved

#38 MAGECLOUD-4047: Eliminate PhpExtension class
  images/php/php-extensions.php
  src/Command/BuildCompose.php
  src/Command/Image/GeneratePhp.php
  src/Compose/Php/ExtensionResolver.php
Labels: approved
