Repository magento/magento-cloud-docker, pull requests merged in 2019-10, with the labels that each got.

#68 MAGECLOUD-4292: FT Take Longer than Before Because of composer/cache …
  images/nginx/1.9/Dockerfile
  images/php/7.0-cli-dev/Dockerfile
  images/php/7.0-cli-dev/bin/cloud-build
  images/php/7.0-cli-dev/docker-entrypoint.sh
  images/php/7.0-cli/Dockerfile
  images/php/7.0-cli/bin/cloud-build
  images/php/7.0-cli/docker-entrypoint.sh
  images/php/7.0-fpm-dev/Dockerfile
  images/php/7.0-fpm-dev/docker-entrypoint.sh
  images/php/7.0-fpm/Dockerfile
  images/php/7.0-fpm/docker-entrypoint.sh
  images/php/7.1-cli-dev/Dockerfile
  images/php/7.1-cli-dev/bin/cloud-build
  images/php/7.1-cli-dev/docker-entrypoint.sh
  images/php/7.1-cli/Dockerfile
  images/php/7.1-cli/bin/cloud-build
  images/php/7.1-cli/docker-entrypoint.sh
  images/php/7.1-fpm-dev/Dockerfile
  images/php/7.1-fpm-dev/docker-entrypoint.sh
  images/php/7.1-fpm/Dockerfile
  images/php/7.1-fpm/docker-entrypoint.sh
  images/php/7.2-cli-dev/Dockerfile
  images/php/7.2-cli-dev/bin/cloud-build
  images/php/7.2-cli-dev/docker-entrypoint.sh
  images/php/7.2-cli/Dockerfile
  images/php/7.2-cli/bin/cloud-build
  images/php/7.2-cli/docker-entrypoint.sh
  images/php/7.2-fpm-dev/Dockerfile
  images/php/7.2-fpm-dev/docker-entrypoint.sh
  images/php/7.2-fpm/Dockerfile
  images/php/7.2-fpm/docker-entrypoint.sh
  images/php/7.3-cli-dev/Dockerfile
  images/php/7.3-cli-dev/bin/cloud-build
  images/php/7.3-cli-dev/docker-entrypoint.sh
  images/php/7.3-cli/Dockerfile
  images/php/7.3-cli/bin/cloud-build
  images/php/7.3-cli/docker-entrypoint.sh
  images/php/7.3-fpm-dev/Dockerfile
  images/php/7.3-fpm-dev/docker-entrypoint.sh
  images/php/7.3-fpm/Dockerfile
  images/php/7.3-fpm/docker-entrypoint.sh
  images/php/cli/Dockerfile
  images/php/cli/bin/cloud-build
  images/php/cli/docker-entrypoint.sh
  images/php/fpm/Dockerfile
  images/php/fpm/docker-entrypoint.sh
  src/Command/Image/GeneratePhp.php
Labels: approved

#67 MAGECLOUD-3968: Add static and unit tests
  .gitignore
  .travis.yml
  composer.json
  images/php/7.0-cli-dev/Dockerfile
  images/php/7.0-cli/Dockerfile
  images/php/7.1-cli-dev/Dockerfile
  images/php/7.1-cli/Dockerfile
  images/php/7.2-cli-dev/Dockerfile
  images/php/7.2-cli/Dockerfile
  images/php/7.3-cli-dev/Dockerfile
  images/php/7.3-cli/Dockerfile
  images/php/cli/Dockerfile
  src/App/GenericException.php
  src/Command/Image/GeneratePhp.php
  src/Compose/DeveloperCompose.php
  src/Compose/FunctionalCompose.php
  src/Compose/Php/ExtensionResolver.php
  src/Compose/ProductionCompose.php
  src/Config/ConfigFactory.php
  src/Config/Dist/Formatter.php
  src/Filesystem/FileList.php
  src/Service/ServiceInterface.php
  tests/README.md
  tests/static/Sniffs/Directives/StrictTypesSniff.php
  tests/static/Sniffs/Whitespace/MultipleEmptyLinesSniff.php
  tests/static/phpcs-ruleset.xml
  tests/static/phpmd-ruleset.xml
  tests/static/phpstan.neon
  tests/unit/.gitignore
  tests/unit/phpunit.xml.dist
Labels: Release: 1.0.0, approved

#64 MAGECLOUD-4053: Windows compatibility is broken
  composer.json
  config/services.xml
  dist/docker-sync.yml
  dist/mutagen.sh
  images/nginx/1.9/etc/vhost.conf
  src/Command/BuildCompose.php
  src/Command/BuildDist.php
  src/Compose/BuilderFactory.php
  src/Compose/BuilderInterface.php
  src/Compose/DeveloperBuilder.php
  src/Compose/DeveloperCompose.php
  src/Compose/FunctionalBuilder.php
  src/Compose/ProductionBuilder.php
  src/Filesystem/DirectoryList.php
  src/Service/ServiceFactory.php
Labels: Release: 1.0.0, approved

#72 MAGECLOUD-4354: [GitHub] Add ionCube Support #70
  images/php/7.1-cli/Dockerfile
  images/php/7.1-fpm/Dockerfile
  images/php/7.2-cli/Dockerfile
  images/php/7.2-fpm/Dockerfile
  images/php/7.3-cli/Dockerfile
  images/php/7.3-fpm/Dockerfile
  src/Compose/Php/ExtensionResolver.php
Labels: Release: 1.0.0, approved

#78 Fix TLS Proxy Timeout
  images/tls/Dockerfile
  images/varnish/4.0/etc/varnish.vcl
  images/varnish/6.2/etc/default.vcl
Labels: Partner: Zilker Technology, Release: 1.0.0, approved, community, improvement, partners-contribution

#84 MAGECLOUD-3979: [Cloud Docker] Exclude large files from docker-sync and mutagen
  dist/docker-sync.yml
  dist/mutagen.sh
  src/Command/BuildCompose.php
Labels: Release: 1.0.0, approved, improvement

#86 Enhance expect exception tests
  composer.json
  src/Test/Unit/Config/Dist/GeneratorTest.php
  src/Test/Unit/Config/Environment/ConverterTest.php
  src/Test/Unit/Config/Environment/ReaderTest.php
  src/Test/Unit/Config/ReaderTest.php
  src/Test/Unit/Config/RelationshipTest.php
  src/Test/Unit/Service/ConfigTest.php
  src/Test/Unit/Service/ServiceFactoryTest.php
Labels: Release: 1.0.0, approved, community, improvement
