Repository magento/magento-cloud-docker, pull requests merged in 2020-06, with the labels that each got.

#224 MCLOUD-6086: Add PHP 7.4 to magento-cloud-docker tests
  .travis.yml
Labels: 1.2, Progress: approved, Release: 1.2.0

#225 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 1.2, Release: 1.2.0

#215 MCLOUD-6008: Include ssh client to make use of ssh-agent forwarding for composer
  dist/bin/magento-docker
  images/php/7.2-cli/Dockerfile
  images/php/7.3-cli/Dockerfile
  images/php/7.4-cli/Dockerfile
  src/Command/Image/GeneratePhp.php
Labels: 1.2, Progress: approved, Release: 1.2.0, documentation-required

#226 MCLOUD-6173: Remove rsyslog from Cloud Docker
  images/php/7.1-cli/Dockerfile
  images/php/7.1-cli/docker-entrypoint.sh
  images/php/7.2-cli/Dockerfile
  images/php/7.2-cli/docker-entrypoint.sh
  images/php/7.3-cli/Dockerfile
  images/php/7.3-cli/docker-entrypoint.sh
  images/php/7.4-cli/Dockerfile
  images/php/7.4-cli/docker-entrypoint.sh
  images/php/cli/docker-entrypoint.sh
  src/Command/Image/GeneratePhp.php
Labels: 1.1, Release: 1.1.0, release-note-completed

#228 Forward-port 1.1 branch
  images/php/7.2-cli/Dockerfile
  images/php/7.2-cli/docker-entrypoint.sh
  images/php/7.3-cli/Dockerfile
  images/php/7.3-cli/docker-entrypoint.sh
  images/php/7.4-cli/Dockerfile
  images/php/7.4-cli/docker-entrypoint.sh
  images/php/cli/docker-entrypoint.sh
  src/Command/Image/GeneratePhp.php
Labels: 1.2, Progress: approved, Release: 1.2.0

#229 MCLOUD-6294: If Mysql set as DB docker set up 3 split DB by default
  src/Config/Source/CliSource.php
  src/Test/Unit/Config/Dist/GeneratorTest.php
Labels: 1.1, Progress: approved, Release: 1.1.0
