Repository magento/magento-cloud-docker, pull requests merged in 2020-01, with the labels that each got.

#111 Added pass for xdebug requests
  images/varnish/4.0/etc/varnish.vcl
  images/varnish/6.2/etc/default.vcl
Labels: Partner: Zilker Technology, Release: 1.0.0, approved, partners-contribution

#118 Deliver 1.0 into develop
  .github/CODE_OF_CONDUCT.md
  images/varnish/4.0/etc/varnish.vcl
  images/varnish/6.2/etc/default.vcl
Labels: approved

#113 MAGECLOUD-4456: Add container healthchecks
  images/elasticsearch/1.7/Dockerfile
  images/elasticsearch/1.7/docker-healthcheck.sh
  images/elasticsearch/2.4/Dockerfile
  images/elasticsearch/2.4/docker-healthcheck.sh
  images/elasticsearch/5.2/Dockerfile
  images/elasticsearch/5.2/docker-healthcheck.sh
  images/elasticsearch/6.5/Dockerfile
  images/elasticsearch/6.5/docker-healthcheck.sh
  src/Command/BuildCompose.php
  src/Compose/BuilderInterface.php
  src/Compose/DeveloperBuilder.php
  src/Compose/FunctionalBuilder.php
  src/Compose/Manager.php
  src/Compose/ManagerFactory.php
  src/Compose/ProductionBuilder.php
  src/Compose/Resolver.php
  src/Service/ServiceFactory.php
Labels: Release: 1.0.1, approved

#119 Bump develop version to 1.1.0
  composer.json
Labels: review

#97 MAGECLOUD-3598: Set Varnish as default cache
  images/php/7.1-cli/bin/cloud-deploy
  images/php/7.2-cli/bin/cloud-deploy
  images/php/7.3-cli/bin/cloud-deploy
  images/php/cli/bin/cloud-deploy
  images/tls/Dockerfile
  src/Command/BuildCompose.php
  src/Compose/BuilderInterface.php
  src/Compose/ProductionBuilder.php
  src/Service/ServiceFactory.php
Labels: Release: 1.1.0, approved

#125 Include ece-post-deploy in command usage
  dist/bin/magento-docker
Labels: Release: 1.0.0, bug

#121 MAGECLOUD-4979: Cleanup Composer Dependencies
  composer.json
Labels: Release: 1.0.0, approved

#133 MAGECLOUD-5063: Cron container stops after starting on 1.0 images #132
  images/php/7.1-cli/docker-entrypoint.sh
  images/php/7.2-cli/docker-entrypoint.sh
  images/php/7.3-cli/docker-entrypoint.sh
  images/php/cli/docker-entrypoint.sh
  src/Compose/ProductionBuilder.php
Labels: Release: 1.0.0, approved

#124 Changed default filesync method in developer mode
  src/Command/BuildCompose.php
Labels: Partner: Zilker Technology, Release: 1.1.0, approved, community, partners-contribution

#134 MAGECLOUD-5101: Forward-port 1.0 branch
  composer.json
  dist/bin/magento-docker
  images/php/7.1-cli/docker-entrypoint.sh
  images/php/7.2-cli/docker-entrypoint.sh
  images/php/7.3-cli/docker-entrypoint.sh
  images/php/cli/docker-entrypoint.sh
  src/Compose/BuilderInterface.php
  src/Compose/ProductionBuilder.php
Labels: approved

#135 MAGECLOUD-5103: Drop Laravel dependency from Cloud Docker
  LICENSE_MIT.txt
  composer.json
  config/services.xml
  src/Command/BuildCompose.php
  src/Command/Image/GeneratePhp.php
  src/Config/Application/Reader.php
  src/Config/Dist/Generator.php
  src/Config/Environment/Shared/Reader.php
  src/Filesystem/FileNotFoundException.php
  src/Filesystem/Filesystem.php
  src/Test/Unit/Config/Application/ReaderTest.php
  src/Test/Unit/Config/Dist/GeneratorTest.php
  src/Test/Unit/Config/Environment/Shared/ReaderTest.php
Labels: Release: 1.0.0, approved

#127 Fixes MCD-100 and MCD-55
  dist/mutagen.sh
Labels: Partner: Zilker Technology, Release: 1.1.0, approved, community, partners-contribution

#130 Custom php.ini from root directory
  images/php/7.1-cli/docker-entrypoint.sh
  images/php/7.1-fpm/docker-entrypoint.sh
  images/php/7.2-cli/docker-entrypoint.sh
  images/php/7.2-fpm/docker-entrypoint.sh
  images/php/7.3-cli/docker-entrypoint.sh
  images/php/7.3-fpm/docker-entrypoint.sh
  images/php/cli/docker-entrypoint.sh
  images/php/fpm/docker-entrypoint.sh
Labels: Partner: Zilker Technology, Release: 1.1.0, approved, community, partners-contribution

#137 Update contributing.md with correct link to CLA
  .github/CONTRIBUTING.md
Labels: Release: 1.1.0, approved

#129 Moved sed substitutions to before the module enables, these were thro…
  images/php/7.1-cli/docker-entrypoint.sh
  images/php/7.1-fpm/docker-entrypoint.sh
  images/php/7.2-cli/docker-entrypoint.sh
  images/php/7.2-fpm/docker-entrypoint.sh
  images/php/7.3-cli/docker-entrypoint.sh
  images/php/7.3-fpm/docker-entrypoint.sh
  images/php/cli/docker-entrypoint.sh
  images/php/fpm/docker-entrypoint.sh
Labels: Partner: Zilker Technology, Release: 1.1.0, approved, community, partners-contribution
