Repository magento/magento-cloud-docker, pull requests merged in 2020-04, with the labels that each got.

#183 MCLOUD-5586: Upgrade Node.js in the PHP container
  images/php/7.1-cli/Dockerfile
  images/php/7.2-cli/Dockerfile
  images/php/7.3-cli/Dockerfile
  images/php/cli/Dockerfile
Labels: Partner: Zilker Technology, Progress: approved, Release: 1.1.0, partners-contribution

#187 MCLOUD-5668: Fix hooks section in Cloud Docker
  src/Config/Source/CloudSource.php
Labels: Progress: approved

#181 MCLOUD-5670: Fix for multiple mysql instance error #169
  src/Config/Source/CloudSource.php
Labels: Partner: Zilker Technology, Progress: approved, Release: 1.1.0, community, partners-contribution

#192 MCLOUD-5709: Add DB access to the CLI
  dist/bin/magento-docker
Labels: Partner: Zilker Technology, Progress: approved, Release: 1.1.0, partners-contribution

#190 MCLOUD-5603: [Investigation] Build images on travis for testing
  .travis.yml
  codeception.dist.yml
  images/redis/3.2/Dockerfile
  images/redis/4.0/Dockerfile
  images/redis/5.0/Dockerfile
  src/Test/Functional/Acceptance/AbstractCest.php
  src/Test/Functional/Acceptance/AcceptanceCest.php
  src/Test/Functional/Acceptance/ElasticsearchCest.php
  src/Test/Functional/Acceptance/SplitDbCest.php
  tests/functional/Codeception/TestInfrastructure.php
  tests/travis/images.sh
Labels: Progress: review

#188 MCLOUD-5752: Healthchecks for nginx and php fpm
  images/nginx/1.9/Dockerfile
  images/nginx/1.9/etc/vhost.conf
  images/nginx/1.9/nginx-healthcheck.sh
  images/php/7.1-fpm/Dockerfile
  images/php/7.1-fpm/etc/php-fpm.conf
  images/php/7.1-fpm/fpm-healthcheck.sh
  images/php/7.2-fpm/Dockerfile
  images/php/7.2-fpm/etc/php-fpm.conf
  images/php/7.2-fpm/fpm-healthcheck.sh
  images/php/7.3-fpm/Dockerfile
  images/php/7.3-fpm/etc/php-fpm.conf
  images/php/7.3-fpm/fpm-healthcheck.sh
  images/php/fpm/Dockerfile
  images/php/fpm/etc/php-fpm.conf
  images/php/fpm/fpm-healthcheck.sh
  src/Compose/ProductionBuilder.php
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
  src/Test/Integration/_files/custom_cloud_base/docker-compose.exp.yml
Labels: Partner: Zilker Technology, Progress: approved, Release: 1.1.0, partners-contribution

#184 MCLOUD-5671: Add cache clearing to CLI
  dist/bin/magento-docker
Labels: Partner: Zilker Technology, Progress: approved, Release: 1.1.0, partners-contribution

#199 MCLOUD-5797: Fix for compose build failing if Blackfire configuration present
  src/Compose/Php/ExtensionResolver.php
Labels: Partner: Zilker Technology, Progress: approved, partners-contribution

#204 MCLOUD-5831 Fix magento-docker entrypoint
  dist/bin/magento-docker
Labels: 1.1, Progress: approved, Release: 1.1.0

#200 MCLOUD-5735: Add support for auto_increment option #195
  src/Command/BuildCompose.php
  src/Compose/ProductionBuilder.php
  src/Config/Config.php
  src/Config/Source/CliSource.php
  src/Config/Source/SourceInterface.php
  src/Test/Integration/BuildComposeTest.php
  src/Test/Integration/BuildCustomComposeTest.php
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
  src/Test/Integration/_files/custom_cloud_base/docker-compose.exp.yml
Labels: 1.1, Progress: approved, Release: 1.1.0

#197 MCLOUD-5818: Fix for composer running out of memory in container
  images/php/7.1-cli/Dockerfile
  images/php/7.2-cli/Dockerfile
  images/php/7.3-cli/Dockerfile
  images/php/cli/Dockerfile
Labels: Partner: Zilker Technology, Progress: approved, Release: 1.1.0, community, partners-contribution

#205 MCLOUD-5855: Added ES 6.8 and 7.6 Support
  images/elasticsearch/6.8/Dockerfile
  images/elasticsearch/6.8/docker-healthcheck.sh
  images/elasticsearch/7.6/Dockerfile
  images/elasticsearch/7.6/docker-healthcheck.sh
Labels: Progress: approved, Release: 1.1.0, release-note-needed

#203 MCLOUD-5856: Added the Healthcheck for DB and redis
  src/Compose/BuilderInterface.php
  src/Compose/ProductionBuilder.php
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
  src/Test/Integration/_files/custom_cloud_base/docker-compose.exp.yml
Labels: Partner: Zilker Technology, Progress: approved, Release: 1.1.0, community, partners-contribution, release-note-completed
