Repository magento/magento-cloud-docker, pull requests merged in 2020-02, with the labels that each got.

#136 MAGECLOUD-5112: Add pcov php extension support into cloud docker
  LICENSE_MIT.txt
  composer.json
  config/services.xml
  images/php/7.1-cli/Dockerfile
  images/php/7.1-cli/etc/php-pcov.ini
  images/php/7.1-fpm/Dockerfile
  images/php/7.1-fpm/etc/php-pcov.ini
  images/php/7.2-cli/Dockerfile
  images/php/7.2-cli/etc/php-pcov.ini
  images/php/7.2-fpm/Dockerfile
  images/php/7.2-fpm/etc/php-pcov.ini
  images/php/7.3-cli/Dockerfile
  images/php/7.3-cli/etc/php-pcov.ini
  images/php/7.3-fpm/Dockerfile
  images/php/7.3-fpm/etc/php-pcov.ini
  images/php/cli/Dockerfile
  images/php/cli/etc/php-pcov.ini
  images/php/fpm/Dockerfile
  images/php/fpm/etc/php-pcov.ini
  src/Command/BuildCompose.php
  src/Command/Image/GeneratePhp.php
  src/Compose/Php/ExtensionResolver.php
  src/Config/Application/Reader.php
  src/Config/Dist/Generator.php
  src/Config/Environment/Shared/Reader.php
  src/Filesystem/FileNotFoundException.php
  src/Filesystem/Filesystem.php
  src/Test/Unit/Config/Application/ReaderTest.php
  src/Test/Unit/Config/Dist/GeneratorTest.php
  src/Test/Unit/Config/Environment/Shared/ReaderTest.php
Labels: Release: 1.1.0, approved

#144 MAGECLOUD-5181: Disable cron container by default
  src/Command/BuildCompose.php
  src/Compose/FunctionalBuilder.php
  src/Compose/ProductionBuilder.php
Labels: Progress: approved, Release: 1.0.0

#138 MAGECLOUD-4170: Add Support for Local Mounts to Production Mode in Cl…
  src/Command/BuildCompose.php
  src/Compose/BuilderInterface.php
  src/Compose/DeveloperBuilder.php
  src/Compose/Manager.php
  src/Compose/ProductionBuilder.php
  src/Compose/ProductionBuilder/VolumeResolver.php
  src/Compose/Resolver.php
Labels: Progress: approved, Progress: review, Release: 1.1.0

#147 MAGECLOUD-5215: Forward-port delivered changes
  src/Command/BuildCompose.php
  src/Compose/BuilderInterface.php
  src/Compose/ProductionBuilder.php
Labels: Progress: approved

#140 MAGECLOUD-4925: Ability to support custom database parameters in docker image
  dist/mysql/mariadb.conf.d/example.cnf
  src/Compose/BuilderInterface.php
  src/Compose/DeveloperBuilder.php
  src/Compose/ProductionBuilder.php
Labels: Progress: approved, Release: 1.1.0, improvement

#145 MAGECLOUD-4922: Email still trying to be sent when ENABLE_SENDMAIL=false is used
  images/php/7.1-cli/docker-entrypoint.sh
  images/php/7.1-cli/etc/mail.ini
  images/php/7.1-fpm/docker-entrypoint.sh
  images/php/7.1-fpm/etc/mail.ini
  images/php/7.2-cli/docker-entrypoint.sh
  images/php/7.2-cli/etc/mail.ini
  images/php/7.2-fpm/docker-entrypoint.sh
  images/php/7.2-fpm/etc/mail.ini
  images/php/7.3-cli/docker-entrypoint.sh
  images/php/7.3-cli/etc/mail.ini
  images/php/7.3-fpm/docker-entrypoint.sh
  images/php/7.3-fpm/etc/mail.ini
  images/php/cli/docker-entrypoint.sh
  images/php/cli/etc/mail.ini
  images/php/fpm/docker-entrypoint.sh
  images/php/fpm/etc/mail.ini
Labels: Progress: approved, Release: 1.1.0

#143 Added Support for Elasticsearch 7.5.2
  images/elasticsearch/7.5/Dockerfile
  images/elasticsearch/7.5/docker-healthcheck.sh
Labels: Partner: Zilker Technology, Progress: approved, Release: 1.1.0, improvement, partners-contribution

#122 xDebug enabled and pre-configured in Developer mode
  images/nginx/1.9/Dockerfile
  images/nginx/1.9/docker-entrypoint.sh
  images/nginx/1.9/etc/vhost.conf
  src/Command/BuildCompose.php
  src/Compose/BuilderInterface.php
  src/Compose/ProductionBuilder.php
  src/Service/ServiceFactory.php
Labels: Partner: Zilker Technology, Progress: approved, Release: 1.1.0, community, partners-contribution

#149 MAGECLOUD-5185: Platform-agnostic Docker builder #102
  .travis.yml
  bin/ece-docker
  bootstrap.php
  composer.json
  config/services.xml
  src/App/Container.php
  src/App/ContainerException.php
  src/App/ContainerInterface.php
  src/App/GenericException.php
  src/Command/BuildCompose.php
  src/Command/BuildDist.php
  src/Command/Image/GeneratePhp.php
  src/Compose/BuilderInterface.php
  src/Compose/DeveloperBuilder.php
  src/Compose/FunctionalBuilder.php
  src/Compose/Php/ExtensionResolver.php
  src/Compose/ProductionBuilder.php
  src/Compose/ProductionBuilder/VolumeResolver.php
  src/Config/Application/Reader.php
  src/Config/Config.php
  src/Config/ConfigFactory.php
  src/Config/Dist/Generator.php
  src/Config/Relationship.php
  src/Config/Source/BaseSource.php
  src/Config/Source/CliSource.php
  src/Config/Source/CloudBaseSource.php
  src/Config/Source/CloudSource.php
  src/Config/Source/SourceException.php
  src/Config/Source/SourceFactory.php
  src/Config/Source/SourceInterface.php
  src/Filesystem/DirectoryList.php
  src/Service/Config.php
  src/Service/ServiceFactory.php
  src/Service/ServiceInterface.php
  src/Test/Integration/BuildComposeTest.php
  src/Test/Integration/_files/.gitignore
  src/Test/Integration/_files/cloud_base/.docker/.gitignore
  src/Test/Integration/_files/cloud_base/.docker/config.php.dist
  src/Test/Integration/_files/cloud_base/.magento.app.yaml
  src/Test/Integration/_files/cloud_base/.magento/services.yaml
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/cloud_base_mftf/.docker/.gitignore
  src/Test/Integration/_files/cloud_base_mftf/.docker/config.php.dist
  src/Test/Integration/_files/cloud_base_mftf/.magento.app.yaml
  src/Test/Integration/_files/cloud_base_mftf/.magento/services.yaml
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
  src/Test/Integration/_files/composer.json
  src/Test/Unit/Config/Application/ReaderTest.php
  src/Test/Unit/Config/Dist/GeneratorTest.php
  src/Test/Unit/Config/RelationshipTest.php
  src/Test/Unit/Service/ConfigTest.php
  src/Test/Unit/Service/ServiceFactoryTest.php
  tests/integration/Container.php
  tests/integration/phpunit.xml.dist
Labels: Progress: approved, Release: 1.1.0

#157 MAGECLOUD-5054: Add single quotes around alpine image in docker-compose.yml
  src/Compose/ProductionBuilder.php
  src/Config/Source/CloudBaseSource.php
  src/Service/ServiceFactory.php
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
Labels: Progress: approved, Release: 1.1.0

#158 MAGECLOUD-5351: WEB docker container does not work in production mode
  images/nginx/1.9/Dockerfile
  images/nginx/1.9/docker-entrypoint.sh
  images/nginx/1.9/etc/nginx.conf
  images/nginx/1.9/etc/vhost.conf
  images/nginx/1.9/etc/xdebug-upstream.conf
  src/Compose/ProductionBuilder.php
  src/Service/ServiceFactory.php
  src/Test/Integration/BuildComposeTest.php
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
Labels: Progress: approved, Release: 1.1.0

#120 MAGECLOUD-4486: Docker functional tests and CI with ece-tools test framework
  .gitignore
  .travis.yml
  codeception.dist.yml
  composer.json
  config/services.xml
  src/Command/BuildCompose.php
  src/Compose/BuilderFactory.php
  src/Compose/DeveloperBuilder.php
  src/Compose/FunctionalBuilder.php
  src/Compose/ProductionBuilder.php
  src/Config/Config.php
  src/Config/Dist/Generator.php
  src/Config/EnvCoder.php
  src/Config/Environment/Shared/Reader.php
  src/Config/Source/CliSource.php
  src/Config/Source/CloudSource.php
  src/Config/Source/SourceInterface.php
  src/Test/Functional/Acceptance.suite.dist.yml
  src/Test/Functional/Acceptance/Acceptance71Cest.php
  src/Test/Functional/Acceptance/Acceptance72Cest.php
  src/Test/Functional/Acceptance/AcceptanceCest.php
  src/Test/Integration/_files/.gitignore
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
  src/Test/Unit/Config/Dist/GeneratorTest.php
  src/Test/Unit/Config/Environment/Shared/ReaderTest.php
  tests/functional/Codeception/BaseModule.php
  tests/functional/Codeception/Docker.php
  tests/functional/Codeception/MagentoDb.php
  tests/functional/Codeception/TestInfrastructure.php
  tests/functional/Robo/Tasks.php
  tests/functional/Robo/Tasks/Bash.php
  tests/functional/Robo/Tasks/CopyFromDocker.php
  tests/functional/Robo/Tasks/CopyToDocker.php
  tests/functional/Robo/Tasks/DockerCompose.php
  tests/functional/Robo/Tasks/DockerCompose/Run.php
  tests/functional/Robo/Tasks/EnvCleanUp.php
  tests/functional/Robo/Tasks/EnvDown.php
  tests/functional/Robo/Tasks/EnvUp.php
  tests/functional/Robo/Tasks/GenerateDockerCompose.php
  tests/functional/Robo/Tasks/RemoveDockerCompose.php
  tests/functional/_data/.gitkeep
  tests/functional/_output/.gitignore
  tests/functional/_support/.gitignore
  tests/functional/_support/CliTester.php
  tests/functional/_support/FailedInfo.php
  tests/functional/configuration.dist.yml
  tests/travis/functional.sh
  tests/travis/static-unit.sh
Labels: Progress: approved, Release: 1.1.0, architecture, improvement
