Repository magento/magento-cloud-docker, pull requests merged in 2020-07, with the labels that each got.

#243 MCLOUD-6338: Magento Quality Patches
  codeception.dist.yml
  tests/functional/Codeception/TestInfrastructure.php
Labels: Progress: approved, Release Line: 1.2

#244 MCLOUD-6338: Magento Quality Patches
  codeception.dist.yml
  tests/functional/Codeception/TestInfrastructure.php
Labels: Progress: approved, Release Line: 1.1

#245 Forward-port 1.1
  src/Config/Source/CliSource.php
Labels: 1.1, Progress: approved

#246 MCLOUD-6199: Cloud Docker Travis is failing on 1.1 branch
  src/Compose/ProductionBuilder.php
Labels: Progress: review, Release Line: 1.1

#247 Improved Builder logic
  src/Compose/ProductionBuilder.php
Labels: Progress: approved, Release Line: 1.2

#251 MCLOUD-6424: Database directories are not creating automatically
  src/Command/BuildCompose.php
  src/Compose/DeveloperBuilder.php
  src/Compose/ProductionBuilder.php
  src/Config/Config.php
  src/Config/Source/CliSource.php
  src/Config/Source/SourceInterface.php
  src/Test/Integration/BuildComposeTest.php
  src/Test/Integration/_files/custom_cloud_base/docker-compose.exp.yml
Labels: Progress: approved, Release Line: 1.1

#253 MCLOUD-6219: Add ES 7.7 image to docker
  images/elasticsearch/7.7/Dockerfile
  images/elasticsearch/7.7/docker-healthcheck.sh
Labels: Progress: approved, Release Line: 1.2, Release: 1.2.0

#254 MCLOUD-6529: Add support for .magento.docker.yml extension
  src/Config/Source/ConfigSource.php
  src/Filesystem/FileList.php
Labels: Progress: done, QA in progress, Release Line: 1.1, Release: 1.1.1

#255 MCLOUD-5624: Unable to enable sending email in the docker
  images/php/7.1-cli/Dockerfile
  images/php/7.1-cli/docker-entrypoint.sh
  images/php/7.1-fpm/Dockerfile
  images/php/7.1-fpm/docker-entrypoint.sh
  images/php/7.2-cli/Dockerfile
  images/php/7.2-cli/docker-entrypoint.sh
  images/php/7.2-fpm/Dockerfile
  images/php/7.2-fpm/docker-entrypoint.sh
  images/php/7.3-cli/Dockerfile
  images/php/7.3-cli/docker-entrypoint.sh
  images/php/7.3-fpm/Dockerfile
  images/php/7.3-fpm/docker-entrypoint.sh
  images/php/7.4-cli/Dockerfile
  images/php/7.4-cli/docker-entrypoint.sh
  images/php/7.4-fpm/Dockerfile
  images/php/7.4-fpm/docker-entrypoint.sh
  images/php/cli/Dockerfile
  images/php/cli/docker-entrypoint.sh
  images/php/fpm/Dockerfile
  images/php/fpm/docker-entrypoint.sh
  src/Command/Image/GeneratePhp.php
  src/Compose/BuilderInterface.php
  src/Compose/ProductionBuilder.php
  src/Config/Source/CloudSource.php
  src/Service/ServiceFactory.php
  src/Service/ServiceInterface.php
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
  src/Test/Integration/_files/custom_cloud_base/docker-compose.exp.yml
Labels: Progress: done, Release Line: 1.1, Release: 1.1.1

#258 Forward-port 1.1 into develop
  images/php/7.2-cli/Dockerfile
  images/php/7.2-cli/docker-entrypoint.sh
  images/php/7.2-fpm/Dockerfile
  images/php/7.2-fpm/docker-entrypoint.sh
  images/php/7.3-cli/Dockerfile
  images/php/7.3-cli/docker-entrypoint.sh
  images/php/7.3-fpm/Dockerfile
  images/php/7.3-fpm/docker-entrypoint.sh
  images/php/7.4-cli/Dockerfile
  images/php/7.4-cli/docker-entrypoint.sh
  images/php/7.4-fpm/Dockerfile
  images/php/7.4-fpm/docker-entrypoint.sh
  images/php/cli/Dockerfile
  images/php/cli/docker-entrypoint.sh
  images/php/fpm/Dockerfile
  images/php/fpm/docker-entrypoint.sh
  src/Command/BuildCompose.php
  src/Command/Image/GeneratePhp.php
  src/Compose/BuilderInterface.php
  src/Compose/DeveloperBuilder.php
  src/Compose/ProductionBuilder.php
  src/Config/Config.php
  src/Config/Source/CliSource.php
  src/Config/Source/CloudSource.php
  src/Config/Source/ConfigSource.php
  src/Config/Source/SourceInterface.php
  src/Filesystem/FileList.php
  src/Service/ServiceFactory.php
  src/Service/ServiceInterface.php
  src/Test/Integration/BuildComposeTest.php
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
  src/Test/Integration/_files/custom_cloud_base/docker-compose.exp.yml
Labels: Progress: ready for delivery, Release Line: 1.2, Release: 1.2.0

#260 MCLOUD-6621: ps library is missing on newer images
  images/php/7.1-cli/Dockerfile
  images/php/7.1-fpm/Dockerfile
  images/php/7.2-cli/Dockerfile
  images/php/7.2-fpm/Dockerfile
  images/php/7.3-cli/Dockerfile
  images/php/7.3-fpm/Dockerfile
  images/php/7.4-cli/Dockerfile
  images/php/7.4-fpm/Dockerfile
  src/Command/Image/GeneratePhp.php
Labels: Progress: ready for delivery, Release Line: 1.1, Release: 1.1.1

#261 Forward-port 1.1 branch into develop
  images/php/7.2-cli/Dockerfile
  images/php/7.2-fpm/Dockerfile
  images/php/7.3-cli/Dockerfile
  images/php/7.3-fpm/Dockerfile
  images/php/7.4-cli/Dockerfile
  images/php/7.4-fpm/Dockerfile
  src/Command/Image/GeneratePhp.php
Labels: Progress: done, Release Line: 1.2, Release: 1.2.0
