Repository magento/magento-cloud-docker, pull requests merged in 2020-03, with the labels that each got.

#164 MAGECLOUD-5486: Magento 2.1 issues in magento-cloud-docker
  images/php/7.1-cli/bin/cloud-deploy
  images/php/7.1-cli/bin/magento-command
  images/php/7.2-cli/bin/cloud-deploy
  images/php/7.2-cli/bin/magento-command
  images/php/7.3-cli/bin/cloud-deploy
  images/php/7.3-cli/bin/magento-command
  images/php/cli/bin/cloud-deploy
  images/php/cli/bin/magento-command
Labels: Progress: approved

#162 MAGECLOUD-5421: [GitHub] Introduce universal configuration file #160
  images/php/7.1-cli/bin/run-hooks
  images/php/7.2-cli/bin/run-hooks
  images/php/7.3-cli/bin/run-hooks
  images/php/cli/bin/run-hooks
  src/Command/BuildCompose.php
  src/Compose/BuilderFactory.php
  src/Compose/ProductionBuilder.php
  src/Compose/ProductionBuilder/VolumeResolver.php
  src/Config/Config.php
  src/Config/Dist/Generator.php
  src/Config/Source/BaseSource.php
  src/Config/Source/CliSource.php
  src/Config/Source/CloudBaseSource.php
  src/Config/Source/CloudSource.php
  src/Config/Source/ConfigSource.php
  src/Config/Source/SourceInterface.php
  src/Filesystem/FileList.php
Labels: Progress: approved, Release: 1.1.0

#163 MAGECLOUD-4168: Provide an Option to Specify Custom URL for Magento
  .travis.yml
  src/Command/BuildCompose.php
  src/Compose/Manager.php
  src/Compose/ManagerFactory.php
  src/Compose/ProductionBuilder.php
  src/Config/Config.php
  src/Config/Dist/Generator.php
  src/Config/Source/BaseSource.php
  src/Config/Source/CliSource.php
  src/Config/Source/SourceInterface.php
  src/Test/Functional/Acceptance/AcceptanceCest.php
  src/Test/Unit/Config/Dist/GeneratorTest.php
  tests/functional/Codeception/BaseModule.php
Labels: Progress: approved, Release: 1.1.0

#170 MAGECLOUD-4919: Ability to run ece-tools on custom github source code
  images/php/7.1-cli/bin/cloud-build
  images/php/7.2-cli/bin/cloud-build
  images/php/7.3-cli/bin/cloud-build
  images/php/cli/bin/cloud-build
  src/Command/BuildCompose.php
  src/Config/Config.php
  src/Config/Source/BaseSource.php
  src/Config/Source/CliSource.php
  src/Config/Source/SourceInterface.php
Labels: Progress: approved, Release: 1.1.0

#161 MAGECLOUD-4894 [MTS] Add support of split DB on docker
  codeception.dist.yml
  composer.json
  dist/mysql-quote/docker-entrypoint-initdb.d/.gitignore
  dist/mysql-sales/docker-entrypoint-initdb.d/.gitignore
  src/Command/BuildCompose.php
  src/Compose/BuilderInterface.php
  src/Compose/ProductionBuilder.php
  src/Config/Config.php
  src/Config/Relationship.php
  src/Config/Source/CliSource.php
  src/Config/Source/CloudSource.php
  src/Config/Source/SourceInterface.php
  src/Service/ServiceFactory.php
  src/Service/ServiceInterface.php
  src/Test/Functional/Acceptance.suite.dist.yml
  src/Test/Functional/Acceptance/AbstractAcceptanceCest.php
  src/Test/Functional/Acceptance/AcceptanceCest.php
  src/Test/Functional/Acceptance/SplitDb71Cest.php
  src/Test/Functional/Acceptance/SplitDb72Cest.php
  src/Test/Functional/Acceptance/SplitDbCest.php
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
  src/Test/Unit/Config/Environment/Shared/ReaderTest.php
  tests/functional/Codeception/BaseModule.php
  tests/functional/Codeception/MagentoDb.php
  tests/functional/Codeception/TestInfrastructure.php
  tests/functional/configuration.dist.yml
Labels: Progress: approved, Release: 1.1.0, release-note-needed

#167 Add Multi-website Support into Cloud Docker
  images/php/7.1-cli/etc/php-cli.ini
  images/php/7.1-fpm/etc/php-fpm.ini
  images/php/7.2-cli/etc/php-cli.ini
  images/php/7.2-fpm/etc/php-fpm.ini
  images/php/7.3-cli/etc/php-cli.ini
  images/php/7.3-fpm/etc/php-fpm.ini
  images/php/cli/etc/php-cli.ini
  images/php/fpm/etc/php-fpm.ini
Labels: Partner: Zilker Technology, Progress: approved, Release: 1.1.0, partners-contribution

#166 MAGECLOUD-3243: OOTB Docker Startup
  bin/init-docker.sh
Labels: Progress: approved, Release: 1.1.0

#168 Fix for conflicting volumes - #43
  src/Compose/DeveloperBuilder.php
  src/Compose/ProductionBuilder.php
  src/Config/Config.php
  src/Config/Source/CloudSource.php
  src/Config/Source/ConfigSource.php
  src/Config/Source/SourceInterface.php
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
Labels: Partner: Zilker Technology, Progress: approved, Release: 1.1.0, partners-contribution

#174 MCLOUD-3059: [Spike] Investigate issue with elasticsearch image on AWS
  images/elasticsearch/1.7/Dockerfile
  images/elasticsearch/2.4/Dockerfile
  images/elasticsearch/5.2/Dockerfile
  images/elasticsearch/6.5/Dockerfile
  images/elasticsearch/7.5/Dockerfile
  src/Command/BuildCompose.php
  src/Compose/ProductionBuilder.php
  src/Config/Source/CliSource.php
  src/Config/Source/SourceInterface.php
  src/Test/Functional/Acceptance/ElasticsearchCest.php
Labels: Progress: approved, Release: 1.1.0

#173 MCLOUD-5535: Add service modification/validation tests
  .travis.yml
  src/Compose/ProductionBuilder.php
  src/Compose/ProductionBuilder/VolumeResolver.php
  src/Config/Config.php
  src/Config/Source/BaseSource.php
  src/Config/Source/SourceInterface.php
  src/Filesystem/FileList.php
  src/Test/Functional/Acceptance/AbstractCest.php
  src/Test/Functional/Acceptance/AcceptanceCest.php
  src/Test/Functional/Acceptance/Elasticsearch72Cest.php
  src/Test/Functional/Acceptance/ElasticsearchCest.php
  src/Test/Functional/Acceptance/Services71Cest.php
  src/Test/Functional/Acceptance/Services72Cest.php
  src/Test/Functional/Acceptance/ServicesCest.php
  src/Test/Functional/Acceptance/SplitDb72Cest.php
  src/Test/Functional/Acceptance/SplitDbCest.php
  src/Test/Integration/_files/cloud_base/composer.json
  src/Test/Integration/_files/cloud_base_mftf/composer.json
  tests/functional/Codeception/BaseModule.php
  tests/functional/Codeception/Docker.php
  tests/functional/Codeception/TestInfrastructure.php
  tests/travis/functional.sh
Labels: Progress: review
