Repository magento/magento-cloud-docker, pull requests merged in 2020-09, with the labels that each got.

#285 MCLOUD-6219: Add ES 7.7 image to docker 1.1
  .travis.yml
  images/elasticsearch/7.7/Dockerfile
  images/elasticsearch/7.7/docker-healthcheck.sh
Labels: Release Line: 1.1, Release: 1.1.2

#286 MCLOUD-6814: [Backport] Improve functional tests execution speed
  .travis.yml
  codeception.dist.yml
  src/Test/Functional/Acceptance/AbstractCest.php
  tests/functional/Codeception/BaseModule.php
  tests/functional/Codeception/TestInfrastructure.php
  travis.php.ini
Labels: Release Line: 1.1, Release: 1.1.2

#282 MCLOUD-6430: Xdebug not working on Magento Cloud Docker 1.1
  images/php/7.2-fpm/Dockerfile
  images/php/7.2-fpm/docker-entrypoint.sh
  images/php/7.3-fpm/Dockerfile
  images/php/7.3-fpm/docker-entrypoint.sh
  images/php/7.4-fpm/Dockerfile
  images/php/7.4-fpm/docker-entrypoint.sh
  images/php/fpm/Dockerfile
  images/php/fpm/docker-entrypoint.sh
  src/Command/BuildCompose.php
  src/Compose/ProductionBuilder.php
  src/Config/Source/CliSource.php
  src/Config/Source/SourceInterface.php
  src/Service/ServiceFactory.php
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
Labels: Progress: testing in progress, Release: 1.2.0

#289 Setup composer 1.10.10 for FT
  .travis.yml
Labels: Progress: review

#290 MCLOUD-6898: Add option to customize port for MailHog
  .gitignore
  codeception.dist.yml
  composer.json
  src/Command/BuildCompose.php
  src/Compose/ProductionBuilder.php
  src/Config/Config.php
  src/Config/Source/BaseSource.php
  src/Config/Source/CliSource.php
  src/Config/Source/SourceInterface.php
  src/Service/ServiceFactory.php
  src/Test/Functional/Acceptance.suite.dist.yml
  src/Test/Functional/Acceptance/MailHogCest.php
  src/Test/Integration/BuildCustomComposeTest.php
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/custom_cloud_base/docker-compose.exp.yml
Labels: Progress: ready for delivery, Release: 1.2.0, release-note-completed
