Repository magento/magento-cloud-docker, pull requests merged in 2020-08, with the labels that each got.

#273 MCLOUD-6469: dh key too small when trying to use magento-cloud-docker-tls
  images/php/7.2-fpm/Dockerfile
  images/php/7.3-fpm/Dockerfile
  images/php/7.4-fpm/Dockerfile
  images/php/fpm/Dockerfile
Labels: Progress: done, Release: 1.2.0

#274 MCLOUD-6660: Add possibility to disable MailHog
  autoload.php
  bootstrap.php
  src/App/Container.php
  src/Command/BuildCompose.php
  src/Compose/ProductionBuilder.php
  src/Config/Source/CliSource.php
  src/Config/Source/CloudSource.php
  src/Config/Source/SourceInterface.php
  src/Filesystem/DirectoryList.php
  src/Test/Integration/BuildCustomComposeTest.php
Labels: Progress: ready for delivery, Release Line: 1.2, Release: 1.2.0

#277 MCLOUD-6469: dh key too small when trying to use magento-cloud-docker…
  .travis.yml
  images/nginx/1.9/nginx-healthcheck.sh
  images/php/7.2-fpm/Dockerfile
  images/php/7.3-fpm/Dockerfile
  images/php/7.4-fpm/Dockerfile
  images/php/fpm/Dockerfile
  images/tls/Dockerfile
  images/tls/certs/magento2.docker.pem
  images/tls/entrypoint.sh
  images/tls/pound.cfg
  images/web/Dockerfile
  images/web/certs/magento.crt
  images/web/certs/magento.key
  images/web/docker-entrypoint.sh
  images/web/etc/nginx.conf
  images/web/etc/vhost.conf
  images/web/etc/xdebug-upstream.conf
  src/Compose/ProductionBuilder.php
  src/Service/ServiceFactory.php
  src/Test/Functional/Acceptance/Services71Cest.php
  src/Test/Functional/Acceptance/Services72Cest.php
  src/Test/Functional/Acceptance/ServicesCest.php
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
  src/Test/Integration/_files/custom_cloud_base/docker-compose.exp.yml
  tests/travis/images.sh
Labels: Progress: ready for delivery, Release: 1.2.0, release-note-completed

#276 MCLOUD-6732: Fix issue with app/etc/env.php on build phase and remove named volumes
  images/php/7.2-cli/bin/cloud-build
  images/php/7.3-cli/bin/cloud-build
  images/php/7.4-cli/bin/cloud-build
  images/php/cli/bin/cloud-build
  src/Compose/BuilderInterface.php
  src/Compose/DeveloperBuilder.php
  src/Compose/ProductionBuilder.php
  src/Compose/ProductionBuilder/VolumeResolver.php
  src/Compose/Resolver.php
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
  src/Test/Integration/_files/custom_cloud_base/docker-compose.exp.yml
Labels: Progress: ready for delivery, Release Line: 1.2, Release: 1.2.0

#280 MCLOUD-6806: Add possibility to access Magento on port 443 inside of …
  images/varnish/4.0/etc/varnish.vcl
  images/varnish/6.2/etc/default.vcl
  images/web/Dockerfile
  images/web/docker-entrypoint.sh
  images/web/etc/vhost.conf
  src/Command/BuildCompose.php
  src/Compose/Manager.php
  src/Compose/ProductionBuilder.php
  src/Config/Config.php
  src/Config/Source/BaseSource.php
  src/Config/Source/CliSource.php
  src/Config/Source/SourceInterface.php
  src/Service/ServiceFactory.php
  src/Test/Integration/BuildComposeTest.php
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
  src/Test/Integration/_files/custom_cloud_base/docker-compose.exp.yml
Labels: Progress: ready for delivery, Release: 1.2.0

#281 MCLOUD-6814: Improve functional tests execution speed
  codeception.dist.yml
  src/Test/Functional/Acceptance/AbstractCest.php
  tests/functional/Codeception/BaseModule.php
  tests/functional/Codeception/TestInfrastructure.php
Labels: Progress: review, Release: 1.2.0

#284 Update links to DevDocs
  README.md
Labels: Progress: review, Release: 1.2.0
