Repository magento/magento-cloud-docker, pull requests merged in 2020-05, with the labels that each got.

#206 MCLOUD-5691: Add support for MySQL #189
  src/Command/BuildCompose.php
  src/Compose/ProductionBuilder.php
  src/Config/Source/CliSource.php
  src/Config/Source/CloudSource.php
  src/Config/Source/SourceInterface.php
  src/Test/Integration/BuildCustomComposeTest.php
Labels: 1.1, Progress: approved, Release: 1.1.0

#208 MCLOUD-5890: Improve Cloud Docker performance
  src/Compose/ProductionBuilder.php
  src/Compose/ProductionBuilder/VolumeResolver.php
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
  src/Test/Integration/_files/custom_cloud_base/docker-compose.exp.yml
Labels: 1.1, Progress: approved, Release: 1.1.0

#212 Forward-port 1.1 branch
  src/Command/BuildCompose.php
  src/Compose/ProductionBuilder.php
  src/Compose/ProductionBuilder/VolumeResolver.php
  src/Config/Source/CliSource.php
  src/Config/Source/CloudSource.php
  src/Config/Source/SourceInterface.php
  src/Test/Integration/BuildCustomComposeTest.php
  src/Test/Integration/_files/cloud_base/docker-compose.exp.yml
  src/Test/Integration/_files/cloud_base_mftf/docker-compose.exp.yml
  src/Test/Integration/_files/custom_cloud_base/docker-compose.exp.yml
Labels: 1.2, Progress: approved, Release: 1.2.0

#207 MCLOUD-5929: Upgrade PHPUnit to version 8
  .travis.yml
  composer.json
  images/php/7.1-cli/Dockerfile
  images/php/7.1-cli/bin/cloud-build
  images/php/7.1-cli/bin/cloud-deploy
  images/php/7.1-cli/bin/cloud-post-deploy
  images/php/7.1-cli/bin/ece-command
  images/php/7.1-cli/bin/magento-command
  images/php/7.1-cli/bin/magento-installer
  images/php/7.1-cli/bin/mftf-command
  images/php/7.1-cli/bin/run-cron
  images/php/7.1-cli/bin/run-hooks
  images/php/7.1-cli/docker-entrypoint.sh
  images/php/7.1-cli/etc/mail.ini
  images/php/7.1-cli/etc/php-cli.ini
  images/php/7.1-cli/etc/php-pcov.ini
  images/php/7.1-cli/etc/php-xdebug.ini
  images/php/7.1-fpm/Dockerfile
  images/php/7.1-fpm/docker-entrypoint.sh
  images/php/7.1-fpm/etc/mail.ini
  images/php/7.1-fpm/etc/php-fpm.conf
  images/php/7.1-fpm/etc/php-fpm.ini
  images/php/7.1-fpm/etc/php-pcov.ini
  images/php/7.1-fpm/etc/php-xdebug.ini
  images/php/7.1-fpm/fpm-healthcheck.sh
  src/Command/Image/GeneratePhp.php
  src/Test/Unit/Config/Dist/GeneratorTest.php
Labels: 1.2, Partner: Zilker Technology, Progress: approved, Release: 1.2.0, partners-contribution

#211 MCLOUD-5980: Increase buffer size for 2.3.5
  images/nginx/1.9/etc/vhost.conf
Labels: 1.1, Progress: approved, Release: 1.1.0

#209 MCLOUD-5982: Added PHP container script (Remove any PHP requirement for Config build)
  dist/bin/magento-docker
Labels: 1.2, Partner: Zilker Technology, Progress: approved, Release: 1.2.0, partners-contribution, release-note-needed

#202 MCLOUD-5857: Added Blackfire support
  images/php/7.2-cli/Dockerfile
  images/php/7.2-fpm/Dockerfile
  images/php/7.3-cli/Dockerfile
  images/php/7.3-fpm/Dockerfile
  images/php/7.4-cli/Dockerfile
  images/php/7.4-fpm/Dockerfile
  src/Compose/Php/ExtensionResolver.php
  src/Compose/ProductionBuilder.php
  src/Config/Config.php
  src/Config/Source/CloudSource.php
  src/Config/Source/SourceInterface.php
  src/Service/ServiceFactory.php
  src/Service/ServiceInterface.php
  src/Test/Integration/_files/cloud_base/.magento.app.yaml
  src/Test/Integration/_files/cloud_base_mftf/.magento.app.yaml
Labels: 1.1, Partner: Zilker Technology, Progress: approved, Progress: changes requested, Progress: review, Release: 1.1.0, community, documentation-required, partners-contribution

#219 MCLOUD-6028: Fix failed tests magento-cloud-docker
  composer.json
  src/Compose/ProductionBuilder.php
Labels: 1.2, Progress: review, Release: 1.2.0

#210 MCLOUD-5981: Added GNUPG extension
  images/php/7.2-cli/Dockerfile
  images/php/7.2-cli/etc/php-gnupg.ini
  images/php/7.2-fpm/Dockerfile
  images/php/7.2-fpm/etc/php-gnupg.ini
  images/php/7.3-cli/Dockerfile
  images/php/7.3-cli/etc/php-gnupg.ini
  images/php/7.3-fpm/Dockerfile
  images/php/7.3-fpm/etc/php-gnupg.ini
  images/php/7.4-cli/Dockerfile
  images/php/7.4-cli/etc/php-gnupg.ini
  images/php/7.4-fpm/Dockerfile
  images/php/7.4-fpm/etc/php-gnupg.ini
  images/php/cli/Dockerfile
  images/php/cli/etc/php-gnupg.ini
  images/php/fpm/Dockerfile
  images/php/fpm/etc/php-gnupg.ini
  src/Compose/Php/ExtensionResolver.php
Labels: 1.2, Partner: Zilker Technology, Progress: approved, Release: 1.2.0, community, partners-contribution

#218 MCLOUD-6043 Fix replace variable WITH_XDEBUG in nginx configuration
  images/nginx/1.9/docker-entrypoint.sh
  images/nginx/1.9/etc/vhost.conf
Labels: 1.2, Progress: approved, Release: 1.2.0, community

#222 Forward-port 1.1 into develop
  images/nginx/1.9/etc/vhost.conf
  images/php/7.2-cli/Dockerfile
  images/php/7.2-fpm/Dockerfile
  images/php/7.3-cli/Dockerfile
  images/php/7.3-fpm/Dockerfile
  images/php/7.4-cli/Dockerfile
  images/php/7.4-fpm/Dockerfile
  src/Compose/Php/ExtensionResolver.php
  src/Compose/ProductionBuilder.php
  src/Config/Config.php
  src/Config/Source/CloudSource.php
  src/Config/Source/SourceInterface.php
  src/Service/ServiceFactory.php
  src/Service/ServiceInterface.php
  src/Test/Integration/_files/cloud_base/.magento.app.yaml
  src/Test/Integration/_files/cloud_base_mftf/.magento.app.yaml
Labels: 1.2, Progress: approved, Release: 1.2.0

#220 Bump the version to 1.2
  composer.json
Labels: 1.2, Progress: approved, Release: 1.2.0
